name: BOB THE BUILDER

on:
  push:
    branches: [ master ]

jobs:
  Bob the Builder builds a new building:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Gather construction materials
      uses: actions/setup-java@v1
      with:
        java-version: 15

    - name: Building roads
      run: echo "${ANDROID_HOME}/build-tools/30.0.1" >> $GITHUB_PATH

    - name: Double-checking construction permit
      run: |
        chmod +x gradlew
        chmod +x alpha-bleed
        chmod +x alpha-bleeding-linux.exe

    - name: BOB THE BUILDER CAN HE FIX IT! BOB THE BUILDER YES HE CAN! (Builds and dexifies mod jar file)
      run: ./gradlew alphableed buildDex

    - name: New building's grand opening.
      uses: actions/upload-artifact@v2.2.1
      with:
        name: Dexed Progressed Materials-ed
        path: build/libs/[!raw-]*.jar